name: Publish Docker image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.G_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push the Docker image
        run: |
          docker build -t ghcr.io/aliyevom/iot-project:latest ./docker  # Adjusted for Dockerfile in the "docker" directory
          docker push ghcr.io/aliyevom/iot-project:latest
