version: '3.8'
services:
  airflow-webserver:
    image: ghcr.io/aliyevom/iot-project:latest
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./dags:/usr/local/airflow/dags  
      - ./logs:/usr/local/airflow/logs  
      - ./plugins:/usr/local/airflow/plugins  
    command: bash -c "airflow webserver" 
    restart: always

  airflow-scheduler:
    image: ghcr.io/aliyevom/iot-project:latest
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver  
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      - ./plugins:/usr/local/airflow/plugins
    command: bash -c "airflow scheduler"  
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
